[general]
import = ["~/.config/alacritty/alacritty.toml"]

[window]
opacity = 0.85
class.instance = "AlacrittyOL"
class.general = "AlacrittyOL"
padding.x = 0
padding.y = 0

[font]
size = 9
# size = 18

[font.normal]
family = "MesloLGS NF"

[cursor]
style = "Beam"
